def artwork():   
    print("\n")
    print("                       \||/         ")
    print("                       |  @___oo   ")
    print("             /\  /\   / (__,,,,|   ")
    print("            ) /^\) ^\/ _)                           Hack the Gmail    ")
    print("            )   /^\/   _)                     CoDeD By:                         ")
    print("            )   _ /  / _)                            XEn0CidE               ")
    print("        /\  )/\/ ||  | )_)                                                     ")
    print("       <  >      |(,,) )__)                                                        ")
    print("        ||      /    \)___)\                                                    ")
    print("        | \____(      )___) )___                                          ")
    print("        \______(_______;;; __;;;                                     ")
    print("\n")
artwork()
